// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdkButton: typeof import('./src/components/AdkButton/AdkButton.vue')['default']
    AdkDivider: typeof import('./src/components/AdkDivider/AdkDivider.vue')['default']
    AdkEmpty: typeof import('./src/components/AdkEmpty/AdkEmpty.vue')['default']
    AnimeCard: typeof import('./src/components/Bangumimini/components/AnimeCard.vue')['default']
    ArticleItem: typeof import('./src/components/ArticleItem/ArticleItem.vue')['default']
    Bangumimini: typeof import('./src/components/Bangumimini/Bangumimini.vue')['default']
    Carousel: typeof import('./src/components/Carousel/Carousel.vue')['default']
    ChatRoom: typeof import('./src/components/ChatRoom/ChatRoom.vue')['default']
    CommentItem: typeof import('./src/components/CommentItem/CommentItem.vue')['default']
    FollowBangumiCard: typeof import('./src/components/FollowBangumiCard/FollowBangumiCard.vue')['default']
    FooterItem: typeof import('./src/components/Footer/FooterItem.vue')['default']
    LoadingAnime: typeof import('./src/components/LoadingAnime/LoadingAnime.vue')['default']
    Logo: typeof import('./src/components/TopNavBar/components/Logo.vue')['default']
    MyEditor: typeof import('./src/components/MyEditor/MyEditor.vue')['default']
    MyElimage: typeof import('./src/components/MyElimage/MyElimage.vue')['default']
    MyPageHeader: typeof import('./src/components/MyPageHeader/MyPageHeader.vue')['default']
    MyPagination: typeof import('./src/components/MyPagination/index.vue')['default']
    PcMenu: typeof import('./src/components/TopNavBar/components/PcMenu.vue')['default']
    Pollup: typeof import('./src/components/TopNavBar/components/Pollup.vue')['default']
    Reply: typeof import('./src/components/CommentItem/components/Reply.vue')['default']
    RightInfoBox: typeof import('./src/components/TopNavBar/components/RightInfoBox.vue')['default']
    SecondComment: typeof import('./src/components/CommentItem/components/SecondComment.vue')['default']
    SmallAnimeItem: typeof import('./src/components/SmallAnimeItem/SmallAnimeItem.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    TagChoose: typeof import('./src/components/TagChoose/TagChoose.vue')['default']
    TagItem: typeof import('./src/components/TagItem/TagItem.vue')['default']
    TagsGroup: typeof import('./src/components/TagsGroup/TagsGroup.vue')['default']
    ThemeConfig: typeof import('./src/components/ThemeConfig/ThemeConfig.vue')['default']
    TopNavBar: typeof import('./src/components/TopNavBar/TopNavBar.vue')['default']
    UploadAvatar: typeof import('./src/components/UploadAvatar/UploadAvatar.vue')['default']
    UploadImage: typeof import('./src/components/UploadImage/UploadImage.vue')['default']
  }
}

export { }
