// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdkButton: typeof import('./src/components/AdkButton/index.vue')['default']
    AdkDivider: typeof import('./src/components/AdkDivider/index.vue')['default']
    AnimeCard: typeof import('./src/components/Bangumimini/components/AnimeCard.vue')['default']
    ArticleItem: typeof import('./src/components/ArticleItem/index.vue')['default']
    Bangumimini: typeof import('./src/components/Bangumimini/index.vue')['default']
    Carousel: typeof import('./src/components/Carousel/index.vue')['default']
    ChatRoom: typeof import('./src/components/ChatRoom/index.vue')['default']
    CommentItem: typeof import('./src/components/CommentItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    LoadingAnime: typeof import('./src/components/LoadingAnime/index.vue')['default']
    Logo: typeof import('./src/components/TopNavBar/components/Logo.vue')['default']
    MyElimage: typeof import('./src/components/MyElimage/index.vue')['default']
    MyEmoji: typeof import('./src/components/MyEmoji/index.vue')['default']
    PcMenu: typeof import('./src/components/TopNavBar/components/PcMenu.vue')['default']
    Pollup: typeof import('./src/components/TopNavBar/components/Pollup.vue')['default']
    RightInfoBox: typeof import('./src/components/TopNavBar/components/RightInfoBox.vue')['default']
    Skin: typeof import('./src/components/Skin.vue')['default']
    SmallAnimeItem: typeof import('./src/components/SmallAnimeItem/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TagChoose: typeof import('./src/components/TagChoose/index.vue')['default']
    TagItem: typeof import('./src/components/TagItem/index.vue')['default']
    TagsGroup: typeof import('./src/components/TagsGroup.vue')['default']
    TopNavBar: typeof import('./src/components/TopNavBar/index.vue')['default']
    UploadAvatar: typeof import('./src/components/UploadAvatar.vue')['default']
  }
}

export { }
