// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdkButton: typeof import('./components/AdkButton/index.vue')['default']
    AdkDivider: typeof import('./components/AdkDivider/index.vue')['default']
    AnimeCard: typeof import('./components/Bangumimini/components/AnimeCard.vue')['default']
    ArticleItem: typeof import('./components/ArticleItem/index.vue')['default']
    Bangumimini: typeof import('./components/Bangumimini/index.vue')['default']
    Carousel: typeof import('./components/Carousel/index.vue')['default']
    ChatRoom: typeof import('./components/ChatRoom/index.vue')['default']
    CommentItem: typeof import('./components/CommentItem.vue')['default']
    Footer: typeof import('./components/Footer/index.vue')['default']
    Logo: typeof import('./components/TopNavBar/components/Logo.vue')['default']
    MyElimage: typeof import('./components/MyElimage/index.vue')['default']
    MyEmoji: typeof import('./components/MyEmoji/index.vue')['default']
    PcMenu: typeof import('./components/TopNavBar/components/PcMenu.vue')['default']
    Pollup: typeof import('./components/TopNavBar/components/Pollup.vue')['default']
    RightInfoBox: typeof import('./components/TopNavBar/components/RightInfoBox.vue')['default']
    Skin: typeof import('./components/Skin.vue')['default']
    SmallAnimeItem: typeof import('./components/SmallAnimeItem/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    TagChoose: typeof import('./components/TagChoose/index.vue')['default']
    TagItem: typeof import('./components/TagItem/index.vue')['default']
    TagsGroup: typeof import('./components/TagsGroup.vue')['default']
    TopNavBar: typeof import('./components/TopNavBar/index.vue')['default']
    UploadAvatar: typeof import('./components/UploadAvatar.vue')['default']
    WelcomePage: typeof import('./components/WelcomePage.vue')['default']
  }
}

export { }
