// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./components/Carousel.vue')['default']
    CommentItem: typeof import('./components/CommentItem.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Skin: typeof import('./components/Skin.vue')['default']
    TagsGroup: typeof import('./components/TagsGroup.vue')['default']
    TopNavBar: typeof import('./components/TopNavBar.vue')['default']
    UploadAvatar: typeof import('./components/UploadAvatar.vue')['default']
    WelcomePage: typeof import('./components/WelcomePage.vue')['default']
  }
}

export { }
